
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action ViewAction;
	private global::Gtk.Action SearchAction;
	private global::Gtk.Action ProjeCtAction;
	private global::Gtk.Action BuildAction;
	private global::Gtk.Action ToolsAction;
	private global::Gtk.Action WindowAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.MenuBar menubar6;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.SearchAction = new global::Gtk.Action ("SearchAction", global::Mono.Unix.Catalog.GetString ("Search"), null, null);
		this.SearchAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Search");
		w1.Add (this.SearchAction, null);
		this.ProjeCtAction = new global::Gtk.Action ("ProjeCtAction", global::Mono.Unix.Catalog.GetString ("Proje ct"), null, null);
		this.ProjeCtAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Proje ct");
		w1.Add (this.ProjeCtAction, null);
		this.BuildAction = new global::Gtk.Action ("BuildAction", global::Mono.Unix.Catalog.GetString ("Build"), null, null);
		this.BuildAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Build");
		w1.Add (this.BuildAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.WindowAction = new global::Gtk.Action ("WindowAction", global::Mono.Unix.Catalog.GetString ("Window"), null, null);
		this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Window");
		w1.Add (this.WindowAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MarkupManipulator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar6'><menu name='FileAction1' action='FileAction1'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='ViewAction' action='ViewAction'/><menu name='SearchAction' action='SearchAction'/><menu name='ProjeCtAction' action='ProjeCtAction'/><menu name='BuildAction' action='BuildAction'/><menu name='ToolsAction' action='ToolsAction'/><menu name='WindowAction' action='WindowAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.menubar6 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar6")));
		this.menubar6.Name = "menubar6";
		this.fixed1.Add (this.menubar6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menubar6]));
		w2.X = -1;
		w2.Y = 3;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 780;
		this.DefaultHeight = 468;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.menubar6.SelectionDone += new global::System.EventHandler (this.Exit);
	}
}
